### ISSUE TITLE
Try to raise an issue

### ISSUE THREAD

**Issue by DinhHo** [nnguyetnam-group/common#12]
Hi anh @nnguyetnam , anh có thấy issue này ko anh ?

**Comment by nnguyetnam** [comment]
Có

Anh reply trực tiếp qua email nè

**Comment by nnguyetnam** [comment]
Định có thể assign và gắn label cho issue này thử xem coi có quyền ko đi.

Thanks,

Nam

**Comment by DinhHo** [comment]
test label and assign feature of git  :)

**Comment by nnguyetnam** [comment]
Nice…

**Comment by nnguyetnam** [comment]
i think it is OK to close it

**Comment by nnguyetnam** [comment]
Test send picture….

**Comment by nnguyetnam** [comment]
![img_3887](https://cloud.githubusercontent.com/assets/13391376/11109336/077a12ac-8922-11e5-8ac1-f83951cdfe4f.JPG)
we must send via web reply...
